/:
  controller: Main
  action: index
  security: false
  role: []

/dashboard:
  controller: Main
  action: dashboard
  security: false
  role: []

/login:
  controller: Security
  action: login
  security: false
  role : []

/dash/home :
  controller: Main
  action: dashboard
  security: true
  role: []

/dash/logout:
  controller: Security
  action: logout
  security: true
  role: [ ]

/dash/user:
  controller: User
  action: listUser
  security: true
  role:
    - 0

/dash/categorie:
  controller: Article
  action: listCategorie
  security: true
  role:
    - 0
    - 1

/dash/article:
  controller: Article
  action: listArticle
  security: true
  role:
    - 0
/dash/addarticle:
  controller: Article
  action: newArticle
  security: true
  role:
    - 0
    - 1

/dash/statusarticle:
  controller: Article
  action: statusArticle
  role:
    - 0

/dash/editarticle:
  controller: Article
  action: editArticle
  security: true
  role:
    - 0
    - 1

/dash/memento:
  controller: Memento
  action: addNew
  security: true
  role:
    - 0
    - 1

/dash/undo:
  controller: Memento
  action: undo
  security: true
  role:
    - 0
    - 1


/dash/newarticle:
  controller: Article
  action: newArticles
  security: true
  role:
    - 0
    - 1

/dash/deletearticle:
  controller: Article
  action: deleteArticle
  security: true
  role:
    - 0

/dash/savememento:
  controller: Memento
  action: saveInMemento
  security: true
  role:
    - 0
    - 1

/dash/versionlist:
  controller: Memento
  action: getVersionList
  security: true
  role:
    - 0
    - 1

/dash/restoreversion:
  controller: Memento
  action: undoContent
  security: true
  role:
    - 0
    - 1

/dash/edituser:
  controller: User
  action: editUser
  security: true
  role: []

/dash/deleteuser:
  controller: User
  action: deleteUser
  security: true
  role: []

/register:
  controller: Security
  action: register

/{slug}:
  controller:  Main
  action: dashboard
  security: true
  role: []

/dash/settings:
  controller: Settings
  action: listMenu
  security: true
  role:
    - 0

/dash/setmenu:
  controller: Settings
  action: setMenu
  security: true
  role:
    - 0